In [ ]:
import numpy as np

In [ ]:
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A=np.random.rand(1)
print(A)

[0.46584502]


In [ ]:
A=np.random.rand(8,4)#rand range is b/w 0 and 1
print(A)

[[0.09907899 0.1598259  0.71504942 0.34729956]
 [0.84639197 0.14582284 0.68671143 0.42395321]
 [0.45224266 0.99970248 0.04310802 0.58339377]
 [0.542621   0.91284503 0.40066622 0.60989855]
 [0.19722872 0.21018408 0.32868864 0.53519215]
 [0.46477612 0.43323041 0.49110677 0.14027071]
 [0.62703084 0.12187961 0.10166665 0.30419094]
 [0.86395801 0.93728822 0.1887755  0.18869618]]


In [ ]:
a=np.floor (10*np.random.rand(8,4))#rand range is b/w 0 and 1
print(a)

[[6. 6. 8. 8.]
 [3. 6. 9. 4.]
 [7. 1. 7. 1.]
 [7. 7. 0. 4.]
 [2. 3. 1. 5.]
 [8. 1. 2. 7.]
 [3. 4. 7. 5.]
 [0. 6. 9. 0.]]


In [ ]:
a=np.arange(1,33).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


SPLLITING AN ARRAY

In [ ]:
np.vsplit(a,4)#split can be done only when the given num is a multiple of number of rows

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.split(a,(2,7))#split after 2nd line and again split after 7th line

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

creating an array with four rows and 8 coloumns

In [ ]:
b=np.arange(1,33).reshape(4,8)
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(b,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(b,(2,6))#splits after second and fifth

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(b,(2,3,6))#splits after 2nd and 3rd and 6th coloumns

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3],
        [11],
        [19],
        [27]]),
 array([[ 4,  5,  6],
        [12, 13, 14],
        [20, 21, 22],
        [28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
b=np.rad2deg(A)#converts radians to degree
print(b)


[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(b)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)


0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)#std=sqrt((sigma(xi-x)^2)/n) where xi=individual elementt and  x=mean n= no of elements

24.452334585202017

In [ ]:
np.var(st)#var=(std)^2

597.9166666666666

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)#linear alzebra is a subpackage in numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(np.argmax(c))#argmax will provide u the index of highest number in each row or coloumn in the given matrix

23


In [ ]:
c=np.floor(10*np.random.rand(24)).reshape(6,4)
print(c)

[[4. 8. 6. 3.]
 [3. 8. 4. 7.]
 [5. 0. 1. 8.]
 [8. 3. 2. 0.]
 [4. 1. 4. 2.]
 [4. 7. 0. 9.]]


In [ ]:
print(np.argmax(c))

23


In [ ]:
d=10*np.random.rand(24).reshape(6,4)
print(d)

[[4.07751998 8.72834794 8.97873355 5.95557456]
 [6.58553538 2.38379297 9.23355193 9.42305738]
 [8.50221714 3.01282204 2.4185026  2.45751048]
 [6.46190302 9.19893241 4.35219561 3.28589104]
 [9.8770008  4.53912116 5.75201058 4.9960637 ]
 [0.1713341  3.35536689 2.15546352 3.97426257]]


In [ ]:
print(np.argmax(d,axis=1))#argmax with axis1 will provide u the index of the highest number in each individual row in the given matrix


[2 3 0 1 0 3]


In [ ]:
print(np.argmax(d,axis=0))#argmax with axis 0 will provide u the index off the highest number in each individual coloumn in the given matrix

[4 3 1 1]


In [ ]:
#we can usemin as like argmax
print(np.argmin(d,axis=1)) arg

[0 1 2 3 1 0]


In [ ]:
print(np.argmin(d,axis=0))

[5 1 5 2]


In [ ]:
#searching the indices based on the conditions
#finding indixes where the values are even
a=np.array([34,56,17,89,91])
print(np.where(a%2==0))

(array([0, 1]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [ ]:
#searching is done only for sorted list
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
#unsortedlist
b=np.array([34,12,7])
x=np.searchsorted(b,7)
print(x)

0


SORTING ARRAY

In [ ]:
arr=np.array(['banana','cherry','apple'])
ar=np.array([True,False,True])#value for false=0 and value for true=1
print(np.sort(arr))
print(np.sort(ar))

['apple' 'banana' 'cherry']
[False  True  True]


In [ ]:
#2d arrayL:sorting happens within a row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#array filters
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]#filter list
newarr=arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

In [ ]:
#iterating through two arrays
names=np.array([" harsha","sada","rohith","josh","abhi"])
initials=np.array(["b","m","u","v","l"])
for i,j in zip(initials,names):
  print(i,".",j)

b .  harsha
m . sada
u . rohith
v . josh
l . abhi


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.multiply(a1,a2)
print(n1)


[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.divide(a1,a2)
print(n1)


[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.mod(a1,a2)
print(n1)


[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.divmod(a1,a2)
print(n1)


(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


LOGORITHMS

In [ ]:
a1=1.2
print(np.log(a1))#natural loge

0.1823215567939546


In [ ]:
a1=1.2
print(np.log2(a1))

0.2630344058337938


In [ ]:
a1=1.2
print(np.log10(a1))#log base 10

0.07918124604762482


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


In [ ]:
#cummulative product
a1=np.array([5,6,7,10])
x=np.cumprod(a1)
print(x)

[   5   30  210 2100]


In [ ]:
a1=np.array([5,6,7,10])
x=np.cumsum(a1)
print(x)

[ 5 11 18 28]


In [ ]:
#difference
a2=np.array([10,15,25,15])
new=np.diff(a2)
print(new)

[  5  10 -10]


In [ ]:
#lcm
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)

8645


In [ ]:
#gcd
n1=455
n2=665
x=np.gcd(n1,n2)
print(x)

35


In [ ]:
#finding gcd for arrays of elements
a=np.array([12,15,60])
gc=np.gcd.reduce(a)#takes multiple inputs and gives single outputs
print(gc)

3


In [ ]:
#find gcd for array of elements
a=np.array([12,15,60])
lc=np.lcm.reduce(a)#takes multiple inputs and gives single output
print(lc)

60
